# Generated by Django 3.0.3 on 2020-08-06 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feeding_entry',
            name='supplement',
        ),
    ]
