# Generated by Django 3.0.3 on 2020-08-06 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feeding', '0002_remove_feeding_entry_supplement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('species', models.CharField(max_length=128)),
                ('age', models.PositiveIntegerField()),
                ('diet', models.CharField(max_length=256)),
                ('profile_pic', models.ImageField(blank=True, upload_to='pet_profile_pics')),
            ],
        ),
    ]
